<?php
require_once("input-upload.php");
require_once("input-faille-xss.php");
require_once("input-name.php");
require_once("input-price.php");
require_once("input-note.php");
require_once("textarea-description.php");
require_once("input-genre.php");
require_once("input-platforms.php");
require_once("input-pegi.php");
